"""Voice channel: the interviewer's questions as speech (text-to-speech), generated once per turn.

`speak` turns one stored interviewer turn into a WAV file under
`<data_dir>/audio/<user_id>/<session_id>/<turn_idx>.wav` and records it in a `TurnAudio` row; every later
call (a replay, a page refresh, History) finds the stored file and costs nothing.

Voice is an extra, never a requirement: every failure (model error, budget reached, disk error) returns a
short notice instead of raising, and the UI then shows the question as text. That is also why `speak` is
called by the UI after a turn is stored, not inside the interview engine: a TTS problem can't fail a turn.

Only the interviewer's own questions are spoken (model output already shown on screen). Coaching tips and
scores belong to candidate turns and are never passed here.
"""

import io
import logging
import os
import shutil
import wave
from collections.abc import Callable
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError
from sqlmodel import func, select

from interview_app.config import Settings
from interview_app.db import InterviewSession, LLMCall, Turn, TurnAudio, session_scope
from interview_app.interview.persona import Channel, SessionConfig
from interview_app.llm.client import LLMClient, LLMError, pcm_format, pcm_seconds
from interview_app.security import check_budget

log = logging.getLogger(__name__)

AUDIO_DIR = "audio"
# Audio of someone's interview is personal data: owner-only, like the database file.
_DIR_MODE = 0o700
_FILE_MODE = 0o600


class SpeechStatus(StrEnum):
    READY = "ready"  # stored earlier, nothing generated
    GENERATED = "generated"  # generated by this call
    TEXT_SESSION = "text_session"  # a Text-channel session: no audio by design
    BUDGET = "budget"  # the session budget is used up, so voice is off (text only)
    FAILED = "failed"  # the model or the disk failed; the turn stays readable as text


@dataclass
class SpeechOutcome:
    status: SpeechStatus
    path: Path | None = None  # the WAV file, when there is one
    notice: str | None = None  # a short message for the UI when there is no audio


BUDGET_NOTICE = "The interview's budget is used up, so the voice is off. The question is shown as text."
FAILED_NOTICE = "The voice could not be generated, so the question is shown as text."


def pcm_to_wav(pcm: bytes, rate: int, channels: int = 1, sample_width: int = 2) -> bytes:
    """Wrap raw little-endian PCM in a WAV header, so a browser's audio player can play it.

    The TTS model returns headerless PCM only; a WAV file is the same samples plus a 44-byte header that
    says the rate, channel count and sample size.
    """
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as wav:
        wav.setnchannels(channels)
        wav.setsampwidth(sample_width)
        wav.setframerate(rate)
        wav.writeframes(pcm)
    return buffer.getvalue()


def session_voice(config: SessionConfig, settings: Settings) -> str:
    """The session's voice: the one stored in its config, else the persona's voice from config.

    New Voice sessions store their voice when they start (preferences.to_session_config), so it stays the
    same for the whole interview; an unknown stored voice (removed from config) falls back to the persona's.
    """
    if config.voice and config.voice in settings.tts.available_voices:
        return config.voice
    return settings.tts.voice_for(config.interview_type.value)


def session_audio_dir(settings: Settings, user_id: int, session_id: int) -> Path:
    # Built from integers only, so no user or model text ever becomes part of a path.
    return settings.data_dir / AUDIO_DIR / str(int(user_id)) / str(int(session_id))


def stored_audio(
    engine: Engine, settings: Settings, user_id: int, session_id: int, turn_idx: int
) -> Path | None:
    """The stored WAV file for a turn, or None. Reads only: never calls a model."""
    with session_scope(engine) as s:
        row = s.exec(
            select(TurnAudio).where(
                TurnAudio.user_id == user_id,
                TurnAudio.session_id == session_id,
                TurnAudio.turn_idx == turn_idx,
            )
        ).first()
        rel = row.path if row else None
    if rel is None:
        return None
    path = settings.data_dir / rel
    return path if path.is_file() else None


def _session_cost(engine: Engine, session_id: int) -> float:
    # Same sum as engine.session_cost; repeated here because the engine imports applications, which
    # imports this module (to delete audio), so importing the engine here would be circular.
    with session_scope(engine) as s:
        total = s.exec(select(func.sum(LLMCall.cost_usd)).where(LLMCall.session_id == session_id)).one()
    return float(total or 0.0)


def _write_private(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True, mode=_DIR_MODE)
    tmp = path.with_suffix(".tmp")
    # Write then rename: a crash mid-write never leaves a half file that looks like finished audio.
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, _FILE_MODE)
    with os.fdopen(fd, "wb") as f:
        f.write(data)
    tmp.replace(path)


def speak(
    engine: Engine,
    settings: Settings,
    make_llm: Callable[[int, int | None], LLMClient],
    user_id: int,
    session_id: int,
    turn_idx: int,
) -> SpeechOutcome:
    """Return the audio of one interviewer turn, generating and storing it on the first call.

    `make_llm` builds a client whose call log is bound to (user_id, session_id) (EngineDeps.make_llm), so
    the TTS cost counts in the session's cost and budget.
    """
    try:
        return _speak(engine, settings, make_llm, user_id, session_id, turn_idx)
    except Exception:
        # Voice must never break the interview. Log the error (no question text, no key) and fall back.
        log.exception("Voice failed for session %s turn %s", session_id, turn_idx)
        return SpeechOutcome(SpeechStatus.FAILED, notice=FAILED_NOTICE)


def _speak(
    engine: Engine,
    settings: Settings,
    make_llm: Callable[[int, int | None], LLMClient],
    user_id: int,
    session_id: int,
    turn_idx: int,
) -> SpeechOutcome:
    with session_scope(engine) as s:
        row = s.exec(
            select(InterviewSession).where(
                InterviewSession.id == session_id, InterviewSession.user_id == user_id
            )
        ).first()
        turn = s.exec(
            select(Turn).where(
                Turn.session_id == session_id,
                Turn.user_id == user_id,
                Turn.idx == turn_idx,
                Turn.speaker == "interviewer",
            )
        ).first()
        config_json = row.config_json if row else None
        text = turn.text if turn else ""
    if config_json is None or not text.strip():
        log.warning("Voice: no interviewer turn %s in session %s for this user", turn_idx, session_id)
        return SpeechOutcome(SpeechStatus.FAILED, notice=FAILED_NOTICE)
    config = SessionConfig.model_validate_json(config_json)
    if config.channel != Channel.VOICE:
        return SpeechOutcome(SpeechStatus.TEXT_SESSION)

    if (path := stored_audio(engine, settings, user_id, session_id, turn_idx)) is not None:
        return SpeechOutcome(SpeechStatus.READY, path)
    # Over budget: skip the voice (text only) rather than close the interview early (spec decision).
    if not check_budget(_session_cost(engine, session_id), settings.limits).allowed:
        return SpeechOutcome(SpeechStatus.BUDGET, notice=BUDGET_NOTICE)

    voice = session_voice(config, settings)
    # Annotated so the code map (reports/tools) can follow the call into the gateway.
    llm: LLMClient = make_llm(user_id, session_id)
    try:
        result = llm.speech("tts", text[: settings.tts.max_chars], model=settings.tts.model, voice=voice)
    except LLMError:
        return SpeechOutcome(SpeechStatus.FAILED, notice=FAILED_NOTICE)  # already logged by the client

    fmt = pcm_format(result.content_type)
    if fmt is not None:
        wav = pcm_to_wav(result.audio, rate=fmt[0], channels=fmt[1])
        seconds = pcm_seconds(result.audio, result.content_type)
    elif "wav" in result.content_type.lower():
        wav, seconds = result.audio, 0.0
    else:
        log.warning("Voice: unexpected audio type %r from %s", result.content_type, settings.tts.model)
        return SpeechOutcome(SpeechStatus.FAILED, notice=FAILED_NOTICE)

    path = session_audio_dir(settings, user_id, session_id) / f"{int(turn_idx)}.wav"
    _write_private(path, wav)
    try:
        with session_scope(engine) as s:
            s.add(
                TurnAudio(
                    session_id=session_id,
                    user_id=user_id,
                    turn_idx=turn_idx,
                    path=str(path.relative_to(settings.data_dir)),
                    voice=voice,
                    model=settings.tts.model,
                    seconds=round(seconds, 2),
                )
            )
    except IntegrityError:
        # Two reruns generated the same turn at once: the other one's row stands (same file path).
        log.info("Voice: audio for session %s turn %s was stored by another run", session_id, turn_idx)
    return SpeechOutcome(SpeechStatus.GENERATED, path)


def delete_session_audio(settings: Settings, user_id: int, session_id: int) -> None:
    """Remove a session's audio files. Its TurnAudio rows go with the session (ON DELETE CASCADE)."""
    folder = session_audio_dir(settings, user_id, session_id)
    if folder.exists():
        shutil.rmtree(folder, ignore_errors=True)
        log.info("Deleted the audio of session %s", session_id)
